# Generated by Django 3.2 on 2022-09-09 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={},
        ),
    ]
